### ISSUE TITLE
i am getting error

### ISSUE THREAD

**Issue by alikorkmaz** [Jacobe2169/ged4py#1]
$ python test.py
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(graph_edit_dist.compare(g,g2))
  File "C:\Users\ali\Documents\Git\ged4py\ged4py\algorithm\graph_edit_dist.py", line 15, in compare
    return ged.normalized_distance()
  File "C:\Users\ali\Documents\Git\ged4py\ged4py\algorithm\abstract_graph_edit_dist.py", line 21, in normalized_distance
    return self.distance() / avg_graphlen
  File "C:\Users\ali\Documents\Git\ged4py\ged4py\algorithm\abstract_graph_edit_dist.py", line 24, in distance
    return sum(self.edit_costs())
  File "C:\Users\ali\Documents\Git\ged4py\ged4py\algorithm\abstract_graph_edit_dist.py", line 27, in edit_costs
    cost_matrix = self.create_cost_matrix()
  File "C:\Users\ali\Documents\Git\ged4py\ged4py\algorithm\abstract_graph_edit_dist.py", line 54, in create_cost_matrix
    cost_matrix[i,j] = self.substitute_cost(nodes1[i], nodes2[j])
  File "C:\Users\ali\AppData\Local\Programs\Python\Python36-32\lib\site-packages\networkx\classes\reportviews.py", line 178, in __getitem__
    return self._nodes[n]
KeyError: 0

i am getting this error message. can you help me ?

**Comment by mwijayaa** [comment]
worked for me with networkx 1.9. But when i tried the latest version networkx, i had same error. 
Maybe you have to try 1.9 version.
